#!/bin/bash
# BRI = overline (proportional), VOL = underline (proportional), text between

# Brightness
bri=$(brightnessctl -m | cut -d, -f4 | tr -d '%')

# Volume
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1 | tr -d '%')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -oP 'yes|no')

# Colors
B="#94e2d5"
if [ "$mute" = "yes" ]; then
    V="#6c7086"
elif [ "$vol" -ge 90 ]; then
    V="#f38ba8"
else
    V="#cba6f7"
fi
E="#313244"

capvol=$((vol > 100 ? 100 : vol))
if [ "$mute" = "yes" ]; then
    vl="MT"
else
    vl="V${vol}%"
fi

# Build label text, pad to fixed width
label=$(printf "B%d%% %s" "$bri" "$vl")
W=${#label}

bf=$((bri * W / 100))
if [ "$mute" = "yes" ]; then
    vf=0
else
    vf=$((capvol * W / 100))
fi

# Find where V or M starts in the label
vpos=$(echo "$label" | grep -bo '[VM]' | head -1 | cut -d: -f1)
vpos=${vpos:-$W}

out=""
for ((i=0; i<W; i++)); do
    ch="${label:$i:1}"
    if ((i < bf)); then ol="%{o${B}}%{+o}"; else ol="%{o${E}}%{+o}"; fi
    if ((i < vf)); then ul="%{u${V}}%{+u}"; else ul="%{u${E}}%{+u}"; fi
    if ((i < vpos)); then fc="%{F${B}}"; else fc="%{F${V}}"; fi
    out+="${ol}${ul}${fc}${ch}%{F-}%{-o}%{-u}"
done

echo "${out}"
